server:
  port: 80

logging:
  config: classpath:logback.xml

app:
  config:
    codoon:
      appKey: 'd6c63b7e0aac11e6bb1700163e000233'
      appSecret: 'd6c63de00aac11e6bb1700163e000233'
      redirectURL: 'http://139.224.2.37/authenticate'
      accessTokenURL: 'https://openapi.codoon.com/token'
      authorizeURL: 'http://openapi.codoon.com/authorize'
      apiBaseURL: 'https://openapi.codoon.com/api/'
      notificationURL: 'http://139.224.2.37/api/codoon/notify/'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jalcohol?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Qtable/114
    initSQL: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
