server:
  port: 9527

logging:
  config: classpath:logback.xml

app:
  config:
    codoon:
      appKey: '3d1602888d5111e29f42782bcb058632'
      appSecret: '3d1606d48d5111e29f42782bcb058632'
      redirectURL: 'http://localhost:9527/authenticate'
      accessTokenURL: 'https://openapi.codoon.com/token'
      authorizeURL: 'http://openapi.codoon.com/authorize'
      apiBaseURL: 'https://openapi.codoon.com/api/'
      crawler:
        agentName: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1'
        loginURL: 'http://sso.codoon.com/login'
        #userName: '18608006515'
        #password: 'qstring1'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jalcohol?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    initSQL: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect